version: '3.8'
services:
  db:
    container_name: mydb
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: 123 # It will eventually be moved to .env
    ports:
      - "1010:5432"